export const TOAST = {
  AUTH: {
    SUCCESS_LOGIN: "LOGIN SUCCESSFULLY!",
    INVALID_LOGIN: "INVALID EMAIL OR PASSWORD",
    ERROR_LOGIN: "LOGIN FAILED, TRY AGAIN",
    SUCCESS_LOGOUT: "LOGOUT SUCCESSFULLY",
    SUCCESS_REGISTER: "REGISTERED SUCCESSFULLY",
    VALIDATION_REGISTER: "PLEASE FILL ALL FIELDS",
    ERROR_REGISTER: "REGISTRATION FAILED!",
    ERROR_LOGOUT: "ERROR OCCURRED DURING LOGOUT.",
  },
  CART: {
    SUCCESS_CART: "PRODUCT ADDED SUCCESSFULLY",
    DELETE_CART: "PRODUCT REMOVED SUCCESSFULLY",
  },
  INBOX: {
    INFO_INBOX: "CHECK EMAIL FOR UPDATES 😊",
    ERROR_INBOX: "MESSAGE FAILED TO SEND",
  },
  CLOUD: {
    SUCCESS_UPLOAD: "IMAGE UPLOADED SUCCESSFULLY",
    ERROR_UPLOAD: "ERROR OCCURRED DURING UPLOAD",
  },
};
