//  AUTH
export const AUTH = "AUTH ";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_ID = "FETCH_USER_ID";
export const LOGOUT = "LOGOUT";

// PRODUCTS
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_ID = "FETCH_PRODUCTS_ID";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

// CART PRODUCTS
export const CREATE_CART_PRODUCT = "CREATE_CART_PRODUCT";
export const FETCH_CART_PRODUCTS = "FETCH_CART_PRODUCTS";
export const FETCH_CART_PRODUCTS_BY_USER_ID = "FETCH_CART_PRODUCTS_BY_USER_ID";
export const DELETE_CART_PRODUCTS = "DELETE_CART_PRODUCTS";
export const DELETE_CART_PRODUCT_BY_USER_ID = "DELETE_CART_PRODUCT_BY_USER_ID";
export const UPDATE_CART_PRODUCTS = "UPDATE_CART_PRODUCTS";

// Orders
export const CREATE_ORDERS = "CREATE_ORDERS";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_BY_USER_ID = "FETCH_ORDERS_BY_USER_ID";
export const DELETE_ORDERS = "DELETE_ORDERS";
export const UPDATE_ORDERS = "UPDATE_ORDERS";

// CATEGORY
export const FETCH_CATEGORY = "FETCH_CATEGORY ";
export const FETCH_CATEGORY_ID = "FETCH_CATEGORY_ID ";

// INBOX
export const CREATE_INBOX = "CREATE_INBOX";
export const FETCH_INBOX = "FETCH_INBOX";
