//  AUTH
export const AUTH = "AUTH ";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_ID = "FETCH_USER_ID";
export const DELETE_USER = "DELETE_USER";
export const LOGOUT = "LOGOUT";

//  INBOX
export const FETCH_INBOX = "FETCH_INBOX";
export const FETCH_INBOX_ID = "FETCH_INBOX_ID";
export const DELETE_INBOX = "DELETE_INBOX";

// PRODUCTS
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_ID = "FETCH_PRODUCTS_ID";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

// CATEGORY
export const FETCH_CATEGORY = "FETCH_CATEGORY ";
export const FETCH_CATEGORY_ID = "FETCH_CATEGORY_ID ";

// ORDERS
export const FETCH_ORDERS = "FETCH_ORDERS ";
export const FETCH_TOTAL = "FETCH_TOTAL ";
export const FETCH_ORDERS_ID = "FETCH_ORDERS_ID ";
export const DELETE_ORDERS = "DELETE_ORDERS ";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS ";

// STATUS
export const FETCH_STATUS = "FETCH_STATUS ";
export const FETCH_STATUS_ID = "FETCH_STATUS_ID ";
