export const TOAST = {
  AUTH: {
    SUCCESS_LOGIN: "LOGIN SUCCESSFULLY!",
    INVALID_LOGIN: "INVALID EMAIL OR PASSWORD",
    ERROR_LOGIN: "LOGIN FAILED, TRY AGAIN",
    SUCCESS_LOGOUT: "LOGOUT SUCCESSFULLY",
    SUCCESS_REGISTER: "REGISTERED SUCCESSFULLY",
    VALIDATION_REGISTER: "PLEASE FILL ALL FIELDS",
    ERROR_REGISTER: "REGISTRATION FAILED!",
    ERROR_LOGOUT: "ERROR OCCURRED DURING LOGOUT.",
    DELETE_USER: "USER DELETED SUCCESSFULLY",
  },
  ORDER: {
    DELETE_ORDER: "ORDER DELETED SUCCESSFULLY",
    ORDER_STATUS: "STATUS UPDATED SUCCESSFULLY",
    ORDER_UPDATE: "ORDER UPDATED SUCCESSFULLY",
  },
  INBOX: {
    DELETE_INBOX: "MESSAGE DELETED SUCCESSFULLY 😊",
  },
  CLOUD: {
    SUCCESS_UPLOAD: "IMAGE UPLOADED SUCCESSFULLY",
    ERROR_UPLOAD: "ERROR OCCURRED DURING UPLOAD",
  },
  PRODUCT: {
    CREATE_PRODUCT: "PRODUCT CREATED SUCCESSFULLY",
    UPDATE_PRODUCT: "PRODUCT UPDATED SUCCESSFULLY",
    DELETE_PRODUCT: "PRODUCT DELETED SUCCESSFULLY",
  },
};
